server:
  port: 8081

logging:
  level:
    org:
      springframework: info
    com:
      oauth2: debug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000