server:
  port: 9000

logging:
  level:
    org:
      springframework: debug
    com:
      oauth2: debug

spring:
  # datasource:
    # url: jdbc:mysql://127.0.0.1:3306/oauth2?createDatabaseIfNotExist=true
    # username: root
    # password: root
    # driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: ${MYSQL_REMOTE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      authorizationserver:

        # impostazioni per client
        client:
          client1:
            registration:
              client-id: client1
              client-secret: "$2a$12$YX2n7OY12cLFIjieZm37EuYvxq14CmlRuNJweK23DLs0DU/chGKIa"
              client-authentication-methods:
                - client_secret_basic
                # - client_secret_jwt
                # - "code"
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/client1
                - http://127.0.0.1:8080/authorized
              # post-logout-redirect-uris:
                # - "http://localhost:8080/logged-out"
              scopes:
                - openid
            # require-authorization-consent: true
